// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvyVOv-JqeKHfxzD2uFAvahH6synpqFfA',
    appId: '1:117068542395:android:08de69062778efca29949e',
    messagingSenderId: '117068542395',
    projectId: 'mcquiz-4d434',
    storageBucket: 'mcquiz-4d434.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXb8ckj0cGkPedZnwUtlcsVX8cYs0o1yk',
    appId: '1:117068542395:ios:ed2fcd607d5d752029949e',
    messagingSenderId: '117068542395',
    projectId: 'mcquiz-4d434',
    storageBucket: 'mcquiz-4d434.firebasestorage.app',
    iosBundleId: 'com.mcquiz.mcquizxam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXb8ckj0cGkPedZnwUtlcsVX8cYs0o1yk',
    appId: '1:117068542395:ios:ed2fcd607d5d752029949e',
    messagingSenderId: '117068542395',
    projectId: 'mcquiz-4d434',
    storageBucket: 'mcquiz-4d434.firebasestorage.app',
    iosBundleId: 'com.mcquiz.mcquizxam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0EeeYeNr2612iFnq39u6EKkERFlX4jsc',
    appId: '1:117068542395:web:ce205f04c9c2251a29949e',
    messagingSenderId: '117068542395',
    projectId: 'mcquiz-4d434',
    authDomain: 'mcquiz-4d434.firebaseapp.com',
    storageBucket: 'mcquiz-4d434.firebasestorage.app',
    measurementId: 'G-ZHXRYTCWR0',
  );
}
